task 1
```{r}
# n is a length of a sequence 
for(n in c(100, 200, 1000)){
  indc <- replicate(1000, grepl("0, 3, 5", toString(sample(0:9, n, replace=T))))
  # now we print sample mean which converges to E[X]
  print(sum(indc)/1000)
}
```
task2
```{r}
tr_num = 1000
# n sequence length
for (n in c(100, 200, 1000)){
  smpl_vctr <- sample(0, tr_num, replace=T)
  # N - num of trials
  for(N in 1:tr_num){
    d_n <- sample(0:9, n, replace=T)
    check_str <- toString(d_n)
    while(grepl("0, 3, 5", check_str)){
      check_str <- sub("0, 3, 5", "", check_str)
       #we add 1 to corresponding entry when there is one more match
      smpl_vctr[N] <- smpl_vctr[N] + 1
    }
  }
  print(mean(smpl_vctr))
}
```
task3
```{r}
len_vec <- sample(0, 1000, replace=T)
for (N in 1:1000){  
  d_n <- sample(0:9, 10000, replace=T)
  for (i in 1:(length(d_n) - 2)){
    if (d_n[i] == 0 && d_n[i+1] == 3 && d_n[i+2] == 5){
      len_vec[N] <- i
      break()
    }
  }
}

print(mean(len_vec))
```
task4
```{r}
#THERE IS A BUG HERE BUT IT SHOLD WORK...
for (n in c(5, 10, 20)){
  mean_vec <- rowMeans(matrix(sample(1:8, n*10000, replace=T), nrow=10000, ncol=n))
  empiric = ecdf(mean_vec)
  #means and sd`s are +- the same here
  theor <- pnorm(seq(min(mean_vec), max(mean_vec), by=.1), mean=mean(mean_vec), sd=sd(mean_vec))
 #we visualise ideal function and an empirical one
  plot(seq(min(mean_vec), max(mean_vec), by=.1), theor, type='l')
  lines(empiric, col="red")
  
  s <- seq(mean(mean_vec)-3*sd(mean_vec), mean(mean_vec)+3*sd(mean_vec), length.out = 200)
  emp_vec <- pnorm(s, mean=mean(mean_vec), sd=sd(mean_vec))
  print(max(abs(empiric(s)-emp_vec)))
  }
```



task5
```{r}
# here everything is the same, but for exp distribution
for (n in c(5, 10, 20)){
  mean_vec <- rowMeans(matrix(rexp(n*10000, rate=8/10), nrow=10000, ncol=n))
  empiric = ecdf(mean_vec)
  theor <- pnorm(seq(min(mean_vec), max(mean_vec), by=.1), mean=mean(mean_vec), sd=sd(mean_vec))
 
  plot(seq(min(mean_vec), max(mean_vec), by=.1), theor, type='l')
  lines(empiric, col="red")
  
  s <- seq(mean(mean_vec)-3*sd(mean_vec), mean(mean_vec)+3*sd(mean_vec), length.out = 200)
  emp_vec <- pnorm(s, mean=mean(mean_vec), sd=sd(mean_vec))
  print(max(abs(empiric(s)-emp_vec)))
  }
```










```{r}
MyData <- read.csv(file="/home/maryana/diabetes.csv", header=TRUE, sep=",")
names(MyData)
Preg <- MyData$Pregnancies
Gluc <-MyData$Glucose
BlPr <- MyData$BloodPressure
SkTh <- MyData$SkinThickness
Insu <- MyData$Insulin
BMI <-MyData$BMI
DPF <- MyData$DiabetesPedigreeFunction
Age <- MyData$Age
Out <- MyData$Outcome

MyData1 <- subset(MyData,Out ==1)
MyData0 <- subset(MyData,Out ==0)
cor0 <- round(cor(MyData0), digits = 2)
cor1 <- round(cor(MyData1), digits = 2)
cor1-cor0

plot(MyData1$Age, MyData1$Preg, col ="green")
points(MyData0$Age, MyData0$Preg, col ="red")

summary(MyData0$Age)

BMIAge <- lm(BMI~Age+Insu)
summary(BMIAge)
plot(BMIAge)
glm(Out~Gluc+BlPr+Insu+Age)
```







































